on:
  push:
    branches:
    - master
name: deploy frontend
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Setup gcloud and deploy
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: |
        gcloud config set project "$GCP_PROJECT_ID"
        gcloud auth activate-service-account grantcm-sa@grantcm.iam.gserviceaccount.com "$GCP_SA_KEY"
        gcloud components install beta --quiet
        cd frontend
        npm install
        ./deploy.sh