name: deploy
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
env:
  PROJECT_ID: grantcm
  SERVICE: grantcm
  REGION: us-central1
jobs:
  deploy:
    # needs: build
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Deploy to Cloud Run
        run: |
          cd frontend
          npm run deploy
