name: lint
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Setup Node
      uses: actions/setup-node@v7
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
        cache-dependency-path: '**/pnpm-lock.yaml'
    - name: Build app
      run: |
        cd frontend
        pnpm install --frozen-lockfile
        pnpm lint
