name: deploy
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
env:
  PROJECT_ID: grantcm
  SERVICE: grantcm
  REGION: us-central1
jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: 'google-github-actions/setup-gcloud@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: Build
        run: |
          cd frontend
          npm install
          npm run build
      - name: Deploy to Cloud Run
        run: |
          cd frontend
          # Disable update check to avoid prompt
          gcloud config set component_manager/disable_update_check true
          npm run deploy
