name: deploy
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
env:
  PROJECT_ID: grantcm
  SERVICE: grantcm
  REGION: us-central1
jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: Build
        run: |
          cd frontend
          npm install
          npm run build
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          source: .
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}